name: fetch-aws-jobs
on:
  schedule:
    - cron: "0 1 * * *" # at 01:00 every day
jobs:
  fetch-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch today's AWS jobs, then call CCJ API route to format jobs and add to DB
        run: |
          data=$(curl "https://www.amazon.jobs/en/search.json?normalized_country_code%5B%5D=USA&business_category%5B%5D=amazon-web-services&result_limit=3")
          curl -L --header "Content-Type: application/json" --header "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}" --request POST --data "$data" "https://cloudcomputingjobs.com/api/cron/aws"
